config {
type: "view",
tags: ["staging"],
database: dataform.projectConfig.vars.project_layer_staging,
schema: dataform.projectConfig.vars.dataset_layer_staging,
description: "Cleaned version of stackoverflow.users table"
}

select
  id as user_id,
  age,
  creation_date,
  round(timestamp_diff(current_timestamp(), creation_date, day)/365) as user_tenure,
  1/0 as deliberate_error  -- << LINHA ADICIONADA PARA CAUSAR ERRO
from
  ${ref("users")}